sport_questions = (
    [
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "Which of the following sports is not part of the triathlon?",
            "correct_answer": "Horse-Riding",
            "incorrect_answers": ["Cycling", "Swimming", "Running"],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "Which English football club has the nickname &#039;The Foxes&#039;?",
            "correct_answer": "Leicester City",
            "incorrect_answers": [
                "Northampton Town",
                "Bradford City",
                "West Bromwich Albion",
            ],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "In baseball, how many fouls are an out?",
            "correct_answer": "0",
            "incorrect_answers": ["5", "3", "2"],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "The Rio 2016 Summer Olympics held it&#039;s closing ceremony on what date?",
            "correct_answer": "August 21",
            "incorrect_answers": ["August 23", "August 19", "August 17"],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "Which country will host the 2020 Summer Olympics?",
            "correct_answer": "Japan",
            "incorrect_answers": ["China", "Australia", "Germany"],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "Which driver has been the Formula 1 world champion for a record 7 times?",
            "correct_answer": "Michael Schumacher",
            "incorrect_answers": ["Ayrton Senna", "Fernando Alonso", "Jim Clark"],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "Which team won 2014 FIFA World Cup in Brazil?",
            "correct_answer": "Germany",
            "incorrect_answers": ["Argentina", "Brazil", "Netherlands"],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "&quot;Stadium of Light&quot; is the home stadium for which soccer team?",
            "correct_answer": "Sunderland FC",
            "incorrect_answers": [
                "Barcelona FC",
                "Paris Saints-Germain",
                "Manchester United",
            ],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "Which country will host the 2022 FIFA World Cup?",
            "correct_answer": "Qatar",
            "incorrect_answers": ["USA", "Japan", "Switzerland"],
        },
        {
            "category": "Sports",
            "type": "multiple",
            "difficulty": "easy",
            "question": "Which two teams played in Super Bowl XLII?",
            "correct_answer": "The New York Giants &amp; The New England Patriots",
            "incorrect_answers": [
                "The Green Bay Packers &amp; The Pittsburgh Steelers",
                "The Philadelphia Eagles &amp; The New England Patriots",
                "The Seattle Seahawks &amp; The Denver Broncos",
            ],
        },
    ],
)
