sport_questions = [
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In golf, what name is given to a hole score of two under par?",
        "correct_answer": "Eagle",
        "incorrect_answers": ["Birdie", "Bogey", "Albatross"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Which English football club has the nickname The Foxes?",
        "correct_answer": "Leicester City",
        "incorrect_answers": [
            "Northampton Town",
            "Bradford City",
            "West Bromwich Albion",
        ],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In baseball, how many fouls are an out?",
        "correct_answer": "0",
        "incorrect_answers": ["5", "3", "2"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Which country will host the 2020 Summer Olympics?",
        "correct_answer": "Japan",
        "incorrect_answers": ["China", "Australia", "Germany"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "How many points did LeBron James score in his first NBA game?",
        "correct_answer": "25",
        "incorrect_answers": ["19", "69", "41"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Who won the 2016 Formula 1 World Driver's Championship?",
        "correct_answer": "Nico Rosberg",
        "incorrect_answers": ["Lewis Hamilton", "Max Verstappen", "Kimi Raikkonen"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "When was the first official international game played?",
        "correct_answer": "1872",
        "incorrect_answers": ["1880", "1863", "1865"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In bowling, what is the term used for getting three consecutive strikes?",
        "correct_answer": "Turkey",
        "incorrect_answers": ["Flamingo", "Birdie", "Eagle"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Who is often called &quot;the Maestro&quot; in the men's tennis circuit?",
        "correct_answer": "Roger Federer",
        "incorrect_answers": ["Bill Tilden", "Boris Becker", "Pete Sampras"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Which African American is in part responsible for integrating  Major League baseball?",
        "correct_answer": "Jackie Robinson",
        "incorrect_answers": ["Curt Flood", "Roy Campanella", "Satchell Paige"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Which player holds the NHL record of 2,857 points?",
        "correct_answer": "Wayne Gretzky",
        "incorrect_answers": ["Mario Lemieux ", "Sidney Crosby", "Gordie Howe"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Who did Steven Gerrard win the Champions League with?",
        "correct_answer": "Liverpool",
        "incorrect_answers": ["Real Madrid", "Chelsea", "Man City"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "The Los Angeles Dodgers were originally from what U.S. city?",
        "correct_answer": "Brooklyn",
        "incorrect_answers": ["Las Vegas", "Boston", "Seattle"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Which country will host the 2022 FIFA World Cup?",
        "correct_answer": "Qatar",
        "incorrect_answers": ["USA", "Japan", "Switzerland"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In the 2014 FIFA World Cup, what was the final score in the match Brazil - Germany?",
        "correct_answer": "1-7",
        "incorrect_answers": ["1-5", "1-6", "2-6"],
    },
]
